# Generated by Django 4.0.4 on 2022-04-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="tag name")),
            ],
            options={
                "verbose_name": "Tags",
                "verbose_name_plural": "Tagss",
            },
        ),
    ]
