# Generated by Django 4.0.4 on 2022-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tags",
            name="count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Count of this tag"
            ),
        ),
    ]
