# Generated by Django 4.0.4 on 2022-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_tags_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Group Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Group description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is group Actve"),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Tags", "verbose_name_plural": "Tags"},
        ),
    ]
