# Generated by Django 4.0.4 on 2022-07-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_group_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="group_extra_questions",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
