# Generated by Django 4.0.4 on 2022-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_group_group_extra_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "question_type",
                    models.CharField(
                        choices=[("text", "Text"), ("number", "Number")],
                        max_length=50,
                        verbose_name="Question Type",
                    ),
                ),
                ("question_mandatory", models.BooleanField(default=False)),
                ("group_question", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="extra_group_questions",
            field=models.ManyToManyField(
                to="common.question", verbose_name="Questions"
            ),
        ),
    ]
