# Generated by Django 4.0.4 on 2022-08-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_group_delete_wait_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Public group "),
        ),
    ]
