server {
    listen      80;
    listen      [::]:80;
    server_name docs.papad.local;

    # security
    include     /etc/nginx/security.conf;

    # logging
    access_log  /var/log/nginx/docs.papad.local.access.log;


    location / {
      proxy_redirect off;
      proxy_set_header Host $proxy_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_pass http://docs;
    }


    # additional config
    include /etc/nginx/general.conf;
}
