server {
    listen      80;
    listen      [::]:80;
    server_name papad.local;

    # security
    include     /etc/nginx/security.conf;

    # logging
    access_log  /var/log/nginx/_.access.log;
    client_max_body_size 100M;

    # UI

    location / {
      root /etc/nginx/static/ui/;
      index index.html;
      try_files $uri /index.html;
    }
     location /auth/login {
      root /etc/nginx/static/ui/;
      index index.html;
      try_files $uri /index.html;
    }
   # app
    location /api/v1/ {
        proxy_pass http://app;
        include    /etc/nginx/proxy.conf;
    }

    location /auth/ {
        proxy_pass http://app;
        include    /etc/nginx/proxy.conf;
    }
    location /static/ {
      alias /etc/nginx/static/ui/static/;
    }
    location /nimda/ {
        proxy_pass http://app;
        include    /etc/nginx/proxy.conf;
    	
    }



    # additional config
    include /etc/nginx/general.conf;
}
