# Generated by Django 4.0.4 on 2022-04-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_reference_id",
                    models.URLField(max_length=500, verbose_name="Media Reference URL"),
                ),
                (
                    "media_target",
                    models.CharField(max_length=100, verbose_name="Media Target"),
                ),
                ("annotation_text", models.TextField(verbose_name="Annotation text")),
                (
                    "annotation_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="annotation",
                        verbose_name="Annotation Reference Image",
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="Public")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tags", models.ManyToManyField(to="common.tags", verbose_name="tags")),
            ],
            options={
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
            },
        ),
    ]
