# Generated by Django 4.0.4 on 2022-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotation",
            options={
                "ordering": ["updated_at"],
                "verbose_name": "Annotation",
                "verbose_name_plural": "Annotations",
            },
        ),
        migrations.AlterField(
            model_name="annotation",
            name="media_target",
            field=models.CharField(
                max_length=100, verbose_name="Media Target(Time start and end)"
            ),
        ),
    ]
