# Generated by Django 4.0.4 on 2022-04-27 18:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0002_alter_annotation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
