# Generated by Django 4.0.4 on 2022-04-27 18:53

from django.db import migrations, models

import papadapi.annotate.models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0003_annotation_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="annotation_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=papadapi.annotate.models.upload_to,
                verbose_name="Annotation Reference Image",
            ),
        ),
    ]
