# Generated by Django 4.0.4 on 2022-04-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0004_alter_annotation_annotation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
