# Generated by Django 4.0.4 on 2022-04-28 19:02

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0005_alter_annotation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2022, 4, 28, 19, 2, 48, 200622, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="annotation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
