# Generated by Django 4.0.4 on 2022-08-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0006_alter_annotation_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Soft Deleted ?"),
        ),
    ]
