# Generated by Django 4.2 on 2023-12-30 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_group_description'),
        ('annotate', '0010_alter_annotation_annotation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.group', verbose_name='Group'),
        ),
    ]
