# Generated by Django 4.2 on 2026-02-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0013_annotation_audio_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="media_reference_id",
            field=models.CharField(max_length=500, verbose_name="Media Reference ID"),
        ),
    ]
