#!/usr/bin/env bash
# deploy-setup.sh — guided production deployment setup
#
# Run once on your server after cloning.
# Generates secrets, writes service_config.env, builds the UI, starts the stack.
#
# Also works for local Docker testing: enter "localhost" as the domain.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOY="$ROOT/deploy"

# ── colours ───────────────────────────────────────────────────────────────────
bold=$'\033[1m'
green=$'\033[32m'
yellow=$'\033[33m'
red=$'\033[31m'
reset=$'\033[0m'

step()  { echo ""; echo "${bold}==> $*${reset}"; }
ok()    { echo "    ${green}ok${reset}  $*"; }
warn()  { echo "    ${yellow}warn${reset} $*"; }
die()   { echo "${red}ERROR: $*${reset}" >&2; exit 1; }
ask()   { printf "    %s " "$1"; read -r "$2"; }

# ── prerequisite check ────────────────────────────────────────────────────────
step "Checking prerequisites"
command -v docker   >/dev/null || die "docker not found — curl -fsSL https://get.docker.com | sh"
command -v python3  >/dev/null || die "python3 not found (needed to generate secrets)"
command -v node     >/dev/null || die "node not found — https://nodejs.org"
command -v npm      >/dev/null || die "npm not found — install with node"
ok "docker, python3, node, npm all present"

# ── existing config guard ─────────────────────────────────────────────────────
CONFIG="$DEPLOY/service_config.env"
FRESH_INSTALL=true
if [ -f "$CONFIG" ]; then
    echo ""
    warn "service_config.env already exists."
    printf "    Overwrite it? [y/N] "
    read -r OVERWRITE
    [[ "$OVERWRITE" =~ ^[Yy]$ ]] || { echo "Aborted. Edit $CONFIG manually."; exit 0; }
    FRESH_INSTALL=false
fi

# ── collect config ────────────────────────────────────────────────────────────
step "Configuration"
echo "    Enter your domain name."
echo "    Production: papad.example.org (no https://)"
echo "    Local Docker test: localhost"
ask "  Domain:" DOMAIN

# Detect local dev mode (localhost or 127.x.x.x)
LOCAL_DEV=false
[[ "$DOMAIN" == "localhost" || "$DOMAIN" =~ ^127\. ]] && LOCAL_DEV=true

echo ""
echo "    MinIO admin username (for the file storage console):"
ask "  MinIO user [admin]:" MINIO_USER
MINIO_USER="${MINIO_USER:-admin}"

echo ""
echo "    Optional: Sentry DSN for error tracking (leave blank to skip):"
ask "  Sentry DSN:" SENTRY_KEY

# ── generate secrets ──────────────────────────────────────────────────────────
step "Generating secrets"
DJANGO_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(50))")
POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_hex(24))")
MINIO_PASSWORD=$(python3 -c "import secrets; print(secrets.token_hex(24))")
CRDT_TOKEN=$(python3 -c "import secrets; print(secrets.token_hex(32))")
ok "DJANGO_SECRET_KEY, POSTGRES_PASSWORD, MINIO_ROOT_PASSWORD, CRDT_SERVER_TOKEN generated"

# ── write service_config.env ──────────────────────────────────────────────────
step "Writing $CONFIG"

if $LOCAL_DEV; then
    PUBLIC_PROTO="http"
    CRDT_PROTO="ws"
else
    PUBLIC_PROTO="https"
    CRDT_PROTO="wss"
fi

cat > "$CONFIG" <<EOF
# Generated by scripts/deploy-setup.sh — keep this file secret, never commit it.

# Django
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
DJANGO_APP_ENV=production

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DB_URL=postgres://papadam:${POSTGRES_PASSWORD}@postgres:5432/papadam

# Redis
REDIS_URL=redis://redis:6379/0

# MinIO
MINIO_ROOT_USER=${MINIO_USER}
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
MINIO_S3_ENDPOINT_URL=http://minio:9000
PAPAD_FILE_STORAGE_TYPE=minio
PAPAD_STORAGE_BUCKET_NAME=papadam
DJANGO_AWS_STORAGE_BUCKET_NAME=papadam

# CRDT server shared secret
CRDT_SERVER_TOKEN=${CRDT_TOKEN}
CRDT_API_URL=http://api:8000

# Public URLs (used by the browser and the SPA)
PUBLIC_API_URL=${PUBLIC_PROTO}://${DOMAIN}
PUBLIC_CRDT_URL=${CRDT_PROTO}://${DOMAIN}/ws

# Domain (used by Caddy --profile webserver only)
DOMAIN=${DOMAIN}

# Error tracking
SENTRY_KEY=${SENTRY_KEY:-}
EOF
ok "wrote $CONFIG"
chmod 600 "$CONFIG"
ok "permissions set to 600 (owner read/write only)"

# Docker Compose reads .env automatically for variable substitution (${VAR} in
# docker-compose.yml). Symlink service_config.env so users never need --env-file.
ln -sf service_config.env "$DEPLOY/.env"
ok "linked deploy/.env → service_config.env (for docker compose variable substitution)"

# ── wipe stale volumes on fresh install ───────────────────────────────────────
# If a previous (failed) run created Docker volumes with different or blank
# credentials, MinIO will refuse to start ("Unknown xl meta version" or auth
# mismatch). Wipe volumes so this run starts clean.
cd "$DEPLOY"
if docker volume ls --format '{{.Name}}' 2>/dev/null | grep -qE "deploy_(pg|minio)-data|papadam.*minio|papadam.*pg"; then
    if $FRESH_INSTALL; then
        step "Removing stale Docker volumes from previous run"
        docker compose --profile minio down -v 2>/dev/null || true
        ok "stale volumes removed — starting clean"
    else
        warn "existing data volumes found — keeping data (update mode)"
        warn "if the stack fails to start, wipe volumes with: docker compose --profile minio down -v"
    fi
fi

# ── build UI ──────────────────────────────────────────────────────────────────
step "Building SvelteKit UI"
cd "$ROOT/ui"
npm install --silent
npm run build
ok "ui/build/ ready"

# ── docker network ────────────────────────────────────────────────────────────
step "Ensuring nginx_network exists"
if $LOCAL_DEV; then
    # For local Docker testing: create a bridge network if it doesn't exist
    docker network create nginx_network 2>/dev/null && ok "created nginx_network" \
        || ok "nginx_network already exists"
else
    # Production: Nginx Proxy Manager creates this; ensure it exists
    docker network create nginx_network 2>/dev/null && ok "created nginx_network" \
        || ok "nginx_network already exists"
fi

# ── start stack ───────────────────────────────────────────────────────────────
step "Starting the stack"
cd "$DEPLOY"
docker compose --profile minio up -d

echo ""
docker compose ps

# ── seed production data ───────────────────────────────────────────────────────
step "Seeding production data"
# Prompt for admin password if not already set in environment
if [ -z "${ADMIN_PASSWORD:-}" ]; then
    printf "    Admin password for '%s': " "${ADMIN_USERNAME:-admin}"
    read -rs ADMIN_PASSWORD
    echo ""
    export ADMIN_PASSWORD
fi
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}" \
ADMIN_PASSWORD="$ADMIN_PASSWORD" \
  docker exec -e ADMIN_USERNAME="${ADMIN_USERNAME:-admin}" \
              -e ADMIN_PASSWORD="$ADMIN_PASSWORD" \
              papadam-api python manage.py seed_prod
ok "production data seeded"

# ── done ──────────────────────────────────────────────────────────────────────
echo ""
echo "${bold}Stack is running.${reset}"
echo ""

if $LOCAL_DEV; then
    echo "${bold}Local Docker setup — access points:${reset}"
    echo "  App:           http://localhost  (needs nginx proxy on :80 → papadam-ui:80)"
    echo "  API:           http://localhost:8000  (if you expose port 8000)"
    echo "  MinIO console: http://localhost:9001"
    echo "                 Login: ${MINIO_USER} / <see service_config.env MINIO_ROOT_PASSWORD>"
    echo ""
    echo "  To expose ports locally, add to docker-compose.yml api service:"
    echo "    ports: ['8000:8000']"
    echo ""
    echo "  Or use the dev workflow (native processes, easier for development):"
    echo "    make setup  # sets up native dev environment"
    echo "    make dev    # starts API + UI + CRDT with hot-reload"
else
    echo "Configure your reverse proxy (see SETUP.md Step 7)."
    echo ""
    echo "Verify the deployment:"
    echo "  curl ${PUBLIC_PROTO}://${DOMAIN}/healthcheck/"
    echo "  curl ${PUBLIC_PROTO}://${DOMAIN}/config.json"
fi
