# Generated by Django 4.0.6 on 2022-08-16 17:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IERequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[("import", "Import"), ("export", "Export")],
                        max_length=50,
                        verbose_name="Request type",
                    ),
                ),
                (
                    "is_authorized",
                    models.BooleanField(default=False, verbose_name="Authorized"),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                ("ie_metadata", models.JSONField(verbose_name="Metadata")),
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="Request ID"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested user",
                    ),
                ),
            ],
        ),
    ]
