# Generated by Django 4.0.6 on 2022-08-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importexport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ierequest",
            name="detail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Request details"
            ),
        ),
    ]
