# Generated by Django 4.0.6 on 2022-08-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importexport", "0002_ierequest_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="ierequest",
            name="requested_file",
            field=models.FileField(
                blank=True, null=True, upload_to="export/", verbose_name="IE File"
            ),
        ),
    ]
