site_name: papadam
site_description: papadam documentation
site_dir: site
copyright: CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - How to Use:
    - Authentication: 'howtouse/authentication'
    - Collections: 'howtouse/dashboard'
    - Groups: 'howtouse/groups'
    - Upload Media: 'howtouse/uploadmedia'
    - Annotation: 'howtouse/annotate'
    - Search and Sort: 'howtouse/search'
    - Exhibits: 'howtouse/exhibits'
  - Instance Admin:
    - Creating superuser: admin/create_admin_user.md
    - Customising the workspace: admin/settings.md
