FROM python:3.12-alpine
ENV PYTHONUNBUFFERED 1

COPY . /app/
COPY startup-bgapps.sh /app/
WORKDIR /app/
RUN pip install --upgrade pip
RUN pip install -r requirements/requirements-prod.txt

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown -R appuser:appgroup /app
USER appuser

CMD ["bash", "startup-bgapps.sh"]
