# Generated by Django 4.0.4 on 2022-04-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="tag name")),
            ],
            options={
                "verbose_name": "Tags",
                "verbose_name_plural": "Tagss",
            },
        ),
        migrations.CreateModel(
            name="MediaStore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FileField(upload_to=None, verbose_name="Uploaded Archive"),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        null=True,
                        verbose_name="Author",
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="Public")),
                (
                    "tags",
                    models.ManyToManyField(to="archive.tags", verbose_name="tags"),
                ),
            ],
            options={
                "verbose_name": "MediaStore",
                "verbose_name_plural": "MediaStores",
            },
        ),
    ]
