# Generated by Django 4.0.4 on 2022-04-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("archive", "0002_alter_mediastore_upload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tags",
        ),
        migrations.AlterField(
            model_name="mediastore",
            name="tags",
            field=models.ManyToManyField(to="common.tags", verbose_name="tags"),
        ),
    ]
