# Generated by Django 4.0.4 on 2022-04-27 18:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0004_mediastore_uuid_alter_mediastore_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediastore",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
