# Generated by Django 4.0.4 on 2022-04-28 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0005_alter_mediastore_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediastore",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mediastore",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
