# Generated by Django 4.0.4 on 2022-05-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0006_mediastore_created_at_mediastore_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediastore",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="mediastore",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
    ]
