# Generated by Django 4.0.4 on 2022-06-29 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_group_alter_tags_options"),
        ("archive", "0007_mediastore_latitude_mediastore_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediastore",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.group",
                verbose_name="Group belonging to",
            ),
        ),
    ]
