# Generated by Django 4.0.4 on 2022-08-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0009_mediastore_extra_group_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediastore",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Soft Deleted ?"),
        ),
    ]
