# Generated by Django 4.0.4 on 2022-08-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0010_mediastore_is_delete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediastore",
            name="author",
        ),
        migrations.RemoveField(
            model_name="mediastore",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="mediastore",
            name="location",
        ),
        migrations.RemoveField(
            model_name="mediastore",
            name="longitude",
        ),
    ]
