# Generated by Django 4.0.6 on 2022-08-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "archive",
            "0011_remove_mediastore_author_remove_mediastore_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mediastore",
            name="is_admin_delete",
            field=models.BooleanField(
                default=False, verbose_name="Admin triggered soft deleted ?"
            ),
        ),
        migrations.AlterField(
            model_name="mediastore",
            name="is_delete",
            field=models.BooleanField(
                default=False, verbose_name="User requested soft delete ?"
            ),
        ),
    ]
