# Generated by Django 4.0.6 on 2022-08-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0012_mediastore_is_admin_delete_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediastore",
            name="is_admin_delete",
        ),
        migrations.AddField(
            model_name="mediastore",
            name="is_instance_admin_withheld",
            field=models.BooleanField(
                default=False, verbose_name="withheld by instance admin?"
            ),
        ),
        migrations.AddField(
            model_name="mediastore",
            name="is_instance_group_withheld",
            field=models.BooleanField(
                default=False, verbose_name="withheld by group admin?"
            ),
        ),
    ]
