# Generated by Django 4.0.4 on 2022-09-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0014_mediastore_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediastore",
            name="extra_group_response",
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
