# Generated by Django 4.0.4 on 2023-02-13 04:54

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_alter_mediastore_extra_group_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediastore',
            name='description',
            field=djrichtextfield.models.RichTextField(verbose_name='Description'),
        ),
    ]
