# Generated by Django 4.2 on 2023-12-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_alter_mediastore_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediastore',
            name='file_extension',
            field=models.CharField(default='', max_length=50, verbose_name='File extension'),
        ),
        migrations.AddField(
            model_name='mediastore',
            name='orig_name',
            field=models.CharField(default='None', max_length=500, verbose_name='Original Media name'),
        ),
        migrations.AddField(
            model_name='mediastore',
            name='orig_size',
            field=models.PositiveIntegerField(default=0, verbose_name='File Size'),
        ),
    ]
