# Generated by Django 4.2 on 2023-12-11 16:45

from django.db import migrations, models

import papadapi.archive.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_mediastore_file_extension_mediastore_orig_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediastore',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=papadapi.archive.models.upload_to, verbose_name='Uploaded Archive'),
        ),
    ]
