# Generated by Django 4.2 on 2023-12-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_alter_mediastore_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediastore',
            name='is_media_processing',
            field=models.BooleanField(default=True, verbose_name='Media is still processing ?'),
        ),
    ]
