# Generated by Django 4.2 on 2023-12-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_mediastore_is_media_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediastore',
            name='is_media_processing',
            field=models.CharField(choices=[('Yet to process', ' Media processing yet to start'), ('Video identified', 'Media identified as Video'), ('Audio identified', 'Media identified as Audio'), ('Processing started', 'Media processing started. This will take a long time.'), ('Processing completed', 'Media processing completed. Stream will be available soon'), ('Processing error', 'Media processing error. Notify admin to take a look at this'), ('Media unknown', 'The uploaded media is not recognized as audio/video. Notify admin if you think this is a mistake'), ('Stream uploading', 'Media streams have started uploading'), ('Stream completed', 'Media streams upload completed'), ('Steam upload error', 'Media streams upload error. Notify admin to take a look at this')], default='Yet to process', max_length=100, verbose_name='Media processing status'),
        ),
    ]
