# Generated by Django 4.2 on 2023-12-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_alter_mediastore_is_media_processing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediastore',
            old_name='is_media_processing',
            new_name='media_processing_status',
        ),
    ]
